"""Pydantic models used by the recommendation service API."""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class RecommendationItem(BaseModel):
    product_id: str = Field(
        ..., description="Identifier of the recommended product in the catalogue."
    )
    reason: str = Field(
        ..., description="Human-readable explanation for why the product was selected."
    )


class RecommendationRequest(BaseModel):
    user_id: str = Field(..., description="Identifier of the authenticated HealZone user.")
    analysis_id: Optional[str] = Field(
        None, description="Optional analysis/result identifier generated by the AI service."
    )
    preferences: Optional[List[str]] = Field(
        None,
        description="Optional keywords describing the user's goals (e.g. hydration, acne, brightening).",
    )
    limit: Optional[int] = Field(
        None,
        ge=1,
        le=50,
        description="Maximum number of recommendations to return (defaults to service configuration).",
    )


class RecommendationResponse(BaseModel):
    data: List[RecommendationItem] = Field(
        default_factory=list,
        description="List of recommended products with accompanying rationale.",
    )
